# Generated by Django 5.2.8 on 2026-04-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
