# Generated by Django 5.2.8 on 2026-04-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_refactor_vehicle_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Инспекция', 'verbose_name_plural': 'Инспекции'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
    ]
