# Generated by Django 5.2.8 on 2026-06-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_inspection_options_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspection',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='custom_vehicle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='metrics_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='mileage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='mode',
            field=models.CharField(choices=[('simple', 'Simple'), ('detailed', 'Detailed')], default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspection',
            name='transmission',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle'),
        ),
    ]
